version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - '8089:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build:
      context: ./
    volumes:
      - ./:/var/www/html
